services:
 dvwa:
   image: vulnerables/web-dvwa
   ports:
     - "8080:80" # DVWA will live at localhost:8080
   restart: unless-stopped
 juice-shop:
   image: bkimminich/juice-shop
   ports:
     - "3000:3000" # Juice Shop will live at localhost:3000
   restart: unless-stopped
